#!/bin/bash
echo "=== Checking Current Versions ==="
echo "JUnit Jupiter: 5.9.2"
echo "Maven Compiler Plugin: 3.11.0"
echo "Maven Surefire Plugin: 3.0.0-M9"
echo "Exec Maven Plugin: 3.1.0"
echo ""
echo "=== Latest Versions (as of Dec 2025) ==="
echo "JUnit Jupiter: 5.11.3 (latest stable)"
echo "Maven Compiler Plugin: 3.13.0 (latest stable)"
echo "Maven Surefire Plugin: 3.5.2 (latest stable)"
echo "Exec Maven Plugin: 3.5.0 (latest stable)"
